# -*- python -*-
Import('env')
import os

sourceFiles = ["../src/" + fn for fn in os.listdir("../src/") if fn.endswith(".cc")]
lsstLibs = "daf_base pex_exceptions pex_policy".split()

env.SharedLibrary(
    'daf_persistence',
    sourceFiles,
    LIBS=env.getlibs("boost jaula coral seal mysqlclient") + lsstLibs,
)

