# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils")
env.LoadableModuleIncomplete("_persistenceLib", Split("persistenceLib.i"),
                             LIBS=env.getlibs("boost utils daf_base pex_exceptions pex_policy coral seal mysqlclient daf_persistence pex_logging"))
