# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils")
LIBS = env.getlibs("boost utils daf_base pex_logging pex_exceptions pex_policy mysqlclient daf_persistence")
env.LoadableModuleIncomplete("_persistenceLib", Split("persistenceLib.i"),
	LIBS=LIBS)

